import 'package:the_smart_workshop/screens/deducts/a-component/const/profiles_name.dart';

import 'const.dart';
import 'data.dart';

List<TurnDeductData> allTurnDeductList = [
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPS,
    cTWindowsProfile: qPS6600,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 2.7,
    cTDeductFrameWithFex: 3.4,
    cTBead: 1.9,
    cTDeductSmallZ: 4.45,
    cTDeductLargeZ: 6.05,
    cTDeductTCenter: -6.2,
    cTWeightFrame: .95,
    cTWeightFrameWithFex: 1.2,
    cTWeightSash: 1.0,
    cTWeightPanda: .86,
    cTWeightT: .86,
    cTWeightBead: .25,
    cTWeightBar: .25,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPS,
    cTWindowsProfile: qPS9600,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 2.7,
    cTDeductFrameWithFex: 3.4,
    cTBead: 1.9,
    cTDeductSmallZ: 4.45,
    cTDeductLargeZ: 6.1,
    cTDeductTCenter: -6.2,
    cTWeightFrame: 1.38,
    cTWeightFrameWithFex: 1.2,
    cTWeightSash: 1.58,
    cTWeightPanda: 1.27,
    cTWeightT: 1.2,
    cTWeightBead: .27,
    cTWeightBar: .25,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qSh,
    cTWindowsProfile: qShSonata,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 2.7,
    cTDeductFrameWithFex: 3.4,
    cTBead: 1.9,
    cTDeductSmallZ: 4.45,
    cTDeductLargeZ: 6.1,
    cTDeductTCenter: -6.2,
    cTWeightFrame: 1.2,
    cTWeightFrameWithFex: 1.5,
    cTWeightSash: 1.25,
    cTWeightPanda: .95,
    cTWeightT: 1.25,
    cTWeightBead: .25,
    cTWeightBar: .25,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qValve,
    cTWindowsProfile: qValveV120,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 3.3,
    cTDeductFrameWithFex: 3.3,
    cTBead: 1.9,
    cTDeductSmallZ: 4.9,
    cTDeductLargeZ: 6.9,
    cTDeductTCenter: -7.7,
    cTWeightFrame: 1.2,
    cTWeightFrameWithFex: 1.5,
    cTWeightSash: 1.3,
    cTWeightPanda: 1.1,
    cTWeightT: 1.2,
    cTWeightBead: .25,
    cTWeightBar: .45,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qFolcano,
    cTWindowsProfile: qFolcano,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 2.82,
    cTDeductFrameWithFex: 3.82,
    cTBead: 1.9,
    cTDeductSmallZ: 4.41,
    cTDeductLargeZ: 6.05,
    cTDeductTCenter: -6.0,
    cTWeightFrame: 1.05,
    cTWeightFrameWithFex: 1.2,
    cTWeightSash: 1.1,
    cTWeightPanda: .9,
    cTWeightT: 1.04,
    cTWeightBead: .26,
    cTWeightBar: .25,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qAlumil,
    cTWindowsProfile: qAlumilM9400,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 3.7,
    cTDeductFrameWithFex: 3.7,
    cTBead: 2.17,
    cTDeductSmallZ: 7.2,
    cTDeductLargeZ: 10.0,
    cTDeductTCenter: -6.0,
    cTWeightFrame: 1.2,
    cTWeightFrameWithFex: 1.2,
    cTWeightSash: 1.75,
    cTWeightPanda: 1.5,
    cTWeightT: 1.2,
    cTWeightBead: .26,
    cTWeightBar: .53,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qAlumil,
    cTWindowsProfile: qAlumilM940,
    cTOneSashDeDuct: 1.2,
    cTTowSashDeDuct: .6,
    cTHeightSashDeduct: 1.2,
    cTDeductFrameWithBar: 2.46,
    cTDeductFrameWithFex: 2.46,
    cTBead: 2.17,
    cTDeductSmallZ: 4.1,
    cTDeductLargeZ: 6.9,
    cTDeductTCenter: -6.0,
    cTWeightFrame: 1.0,
    cTWeightFrameWithFex: .75,
    cTWeightSash: .97,
    cTWeightPanda: .76,
    cTWeightT: .77,
    cTWeightBead: .26,
    cTWeightBar: .53,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPVC,
    cTWindowsProfile: qEnderPen,
    cTOneSashDeDuct: 1.6,
    cTTowSashDeDuct: .8,
    cTHeightSashDeduct: 1.6,
    cTDeductFrameWithBar: 4.2,
    cTDeductFrameWithFex: 3.7,
    cTBead: 0.0,
    cTDeductSmallZ: 5.8,
    cTDeductLargeZ: 8.5,
    cTDeductTCenter: -7.3,
    cTWeightFrame: 0.0,
    cTWeightFrameWithFex: 0.0,
    cTWeightSash: 0.0,
    cTWeightPanda: 0.0,
    cTWeightT: 0.0,
    cTWeightBead: 0.0,
    cTWeightBar: 0.0,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPVC,
    cTWindowsProfile: qPolyWin,
    cTOneSashDeDuct: 1.6,
    cTTowSashDeDuct: .8,
    cTHeightSashDeduct: 1.6,
    cTDeductFrameWithBar: 3.1,
    cTDeductFrameWithFex: 3.7,
    cTBead: 0.0,
    cTDeductSmallZ: 5.8,
    cTDeductLargeZ: 8.8,
    cTDeductTCenter: -7.3,
    cTWeightFrame: 0.0,
    cTWeightFrameWithFex: 0.0,
    cTWeightSash: 0.0,
    cTWeightPanda: 0.0,
    cTWeightT: 0.0,
    cTWeightBead: 0.0,
    cTWeightBar: 0.0,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPVC,
    cTWindowsProfile: qComPen,
    cTOneSashDeDuct: 1.6,
    cTTowSashDeDuct: .8,
    cTHeightSashDeduct: 1.6,
    cTDeductFrameWithBar: 3.1,
    cTDeductFrameWithFex: 3.4,
    cTBead: 0.0,
    cTDeductSmallZ: 6.2,
    cTDeductLargeZ: 8.5,
    cTDeductTCenter: -9.1,
    cTWeightFrame: 0.0,
    cTWeightFrameWithFex: 0.0,
    cTWeightSash: 0.0,
    cTWeightPanda: 0.0,
    cTWeightT: 0.0,
    cTWeightBead: 0.0,
    cTWeightBar: 0.0,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPVC,
    cTWindowsProfile: qWintech60,
    cTOneSashDeDuct: 1.6,
    cTTowSashDeDuct: .8,
    cTHeightSashDeduct: 1.6,
    cTDeductFrameWithBar: 4.3,
    cTDeductFrameWithFex: 3.4,
    cTBead: 0.0,
    cTDeductSmallZ: 5.6,
    cTDeductLargeZ: 8.4,
    cTDeductTCenter: -7.3,
    cTWeightFrame: 0.0,
    cTWeightFrameWithFex: 0.0,
    cTWeightSash: 0.0,
    cTWeightPanda: 0.0,
    cTWeightT: 0.0,
    cTWeightBead: 0.0,
    cTWeightBar: 0.0,
  }),
  TurnDeductData({
    cTCountry: 'egypt',
    cTSystemType: qPVC,
    cTWindowsProfile: qWintech330,
    cTOneSashDeDuct: 1.6,
    cTTowSashDeDuct: .8,
    cTHeightSashDeduct: 1.6,
    cTDeductFrameWithBar: 3.2,
    cTDeductFrameWithFex: 4.0,
    cTBead: 0.0,
    cTDeductSmallZ: 5.6,
    cTDeductLargeZ: 9.5,
    cTDeductTCenter: -7.3,
    cTWeightFrame: 0.0,
    cTWeightFrameWithFex: 0.0,
    cTWeightSash: 0.0,
    cTWeightPanda: 0.0,
    cTWeightT: 0.0,
    cTWeightBead: 0.0,
    cTWeightBar: 0.0,
  }),
];
