import '../unit_data.dart';

List<UnitData> cornerUnit = [
  UnitData(
      unitId: 0,
      imageId: 4001,
      unitName: 'ركنة سفلي',
      widthShutterLength: 1,
      heightShutterLength: 1,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 1,
      isNew: true),
  UnitData(
      unitId: 1,
      imageId: 4002,
      unitName: 'ركنة 90 سفلي',
      widthShutterLength: 2,
      heightShutterLength: 1,
      widthMultiShutterLength: 2,
      heightMultiShutterLength: 1,
      rackLength: 1,
      is90: true,
      isNew: true),
  UnitData(
      unitId: 2,
      imageId: 4003,
      unitName: 'درفتين سفلي',
      widthShutterLength: 2,
      heightShutterLength: 1,
      widthMultiShutterLength: 2,
      heightMultiShutterLength: 1,
      rackLength: 1,
      isNew: true),
  UnitData(
      unitId: 3,
      imageId: 4101,
      unitType: 1,
      unitName: 'ركنة علوي',
      widthShutterLength: 1,
      heightShutterLength: 1,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      isNew: true),
  UnitData(
      unitId: 4,
      imageId: 4102,
      unitType: 1,
      unitName: 'ركنة 90 علوي',
      widthShutterLength: 1,
      heightShutterLength: 1,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 1,
      is90: true,
      isNew: true),
  UnitData(
      unitId: 5,
      imageId: 4103,
      unitType: 1,
      unitName: 'درفتين علوي',
      widthShutterLength: 2,
      heightShutterLength: 1,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 1,
      isNew: true),
  UnitData(
      unitId: 6,
      imageId: 4201,
      unitName: 'نهاية سفلي',
      widthShutterLength: 1,
      heightShutterLength: 1,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 1,
      isEnd: true,
      isNew: true),
  UnitData(
      unitId: 7,
      imageId: 4202,
      unitType: 1,
      unitName: 'نهاية علوي',
      widthShutterLength: 1,
      heightShutterLength: 1,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 1,
      isEnd: true,
      isNew: true),
];
