import '../unit_data.dart';

List<UnitData> cupboardUnit = [
  UnitData(
      unitId: 0,
      imageId: 3002,
      unitName: 'دولاب درفة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isMultiHeight: true,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 3,
      isNew: true),
  UnitData(
      unitId: 1,
      imageId: 3004,
      unitName: 'دولاب درفتين',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isMultiHeight: true,
      widthMultiShutterLength: 2,
      heightMultiShutterLength: 1,
      rackLength: 3,
      isNew: true),
  UnitData(
      unitId: 2,
      imageId: 3003,
      unitName: 'دولاب بفرن',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isMultiHeight: true,
      isOpened: true,
      widthMultiShutterLength: 2,
      heightMultiShutterLength: 1,
      isNew: true),
  UnitData(
      unitId: 3,
      imageId: 3006,
      unitName: 'درفة وأدراج',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isMultiHeight: true,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      isDrawer: true,
      withoutShutter: true,
      drawerLength: 4,
      rackLength: 2,
      isNew: true),
  UnitData(
      unitId: 4,
      imageId: 3005,
      unitName: 'درفتين وأدراج',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isMultiHeight: true,
      widthMultiShutterLength: 2,
      heightMultiShutterLength: 1,
      isDrawer: true,
      rackLength: 2,
      withoutShutter: true,
      drawerLength: 4,
      isNew: true),
  UnitData(
      unitId: 5,
      imageId: 3008,
      unitName: 'درفة طويلة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isMultiHeight: true,
      isBigLowerHeight: true,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 3,
      isNew: true),
  UnitData(
      unitId: 6,
      imageId: 3007,
      unitName: 'درفتين وقلاب',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isMultiHeight: true,
      isBigLowerHeight: true,
      widthMultiShutterLength: 1,
      heightMultiShutterLength: 1,
      rackLength: 3,
      isNew: true),
  UnitData(
      unitId: 7,
      imageId: 3001,
      unitName: 'درفة كاملة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      rackLength: 4,
      isNew: true),
  UnitData(
      unitId: 8,
      imageId: 3010,
      unitName: 'درفتين كاملة',
      widthShutterLength: 2,
      heightShutterLength: 1,
      rackLength: 4,
      isNew: true),
  UnitData(
      unitId: 9,
      imageId: 3009,
      unitName: 'درفتين وفرن',
      widthShutterLength: 2,
      heightShutterLength: 1,
      rackLength: 1,
      isOpened: true,
      isNew: true),
];
