import '../unit_data.dart';

List<UnitData> lowerUnit = [
  UnitData(
    unitId: 0,
    imageId: 1001,
    unitName: 'درفة واحدة',
    widthShutterLength: 1,
    heightShutterLength: 1,
  ),
  UnitData(
    unitId: 1,
    imageId: 1003,
    unitName: 'درفتين',
    widthShutterLength: 2,
    heightShutterLength: 1,
  ),
  UnitData(
      unitId: 2,
      imageId: 1002,
      unitName: 'درج ودرفة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isDrawer: true,
      drawerLength: 1),
  UnitData(
      unitId: 3,
      imageId: 1004,
      unitName: 'درج ودرفتين',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isDrawer: true,
      drawerLength: 1),
  UnitData(
      unitId: 4,
      imageId: 1005,
      unitName: 'درفتين أفقي',
      widthShutterLength: 1,
      heightShutterLength: 2,
      rackLength: 0),
  UnitData(
      unitId: 5,
      imageId: 1005,
      unitName: 'درجين علبة',
      widthShutterLength: 1,
      heightShutterLength: 2,
      isShutterWithDrawer: true,
      isNew: true,
      rackLength: 0),
  UnitData(
      unitId: 6,
      imageId: 1006,
      unitName: 'درجين ودرفة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isDrawer: true,
      rackLength: 0,
      drawerLength: 2),
  UnitData(
      unitId: 7,
      imageId: 1006,
      unitName: 'درجين ودرج',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isShutterWithDrawer: true,
      isDrawer: true,
      rackLength: 0,
      isNew: true,
      drawerLength: 2),
  UnitData(
      unitId: 8,
      imageId: 1014,
      unitName: 'بدون درفة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      withoutShutter: true),
  UnitData(
      unitId: 9,
      imageId: 1008,
      unitName: '3 درج',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isDrawer: true,
      rackLength: 0,
      drawerLength: 3,
      withoutShutter: true),
  UnitData(
      unitId: 10,
      imageId: 1009,
      unitName: '4 درج',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isDrawer: true,
      rackLength: 0,
      drawerLength: 4,
      withoutShutter: true),
  UnitData(
      unitId: 11,
      imageId: 1010,
      unitName: '5 درج',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isDrawer: true,
      rackLength: 0,
      drawerLength: 5,
      withoutShutter: true),
  UnitData(
      unitId: 12,
      imageId: 1007,
      unitName: 'درج ودرفتين',
      widthShutterLength: 1,
      heightShutterLength: 2,
      rackLength: 0,
      isDrawer: true,
      drawerLength: 1),
  UnitData(
      unitId: 13,
      imageId: 1007,
      unitName: 'درج ودرجين',
      widthShutterLength: 1,
      heightShutterLength: 2,
      rackLength: 0,
      isDrawer: true,
      isShutterWithDrawer: true,
      isNew: true,
      drawerLength: 1),
  UnitData(
      unitId: 14,
      imageId: 1011,
      unitName: 'درج وفرن',
      widthShutterLength: 1,
      heightShutterLength: 1,
      withoutShutter: true,
      isOpened: true,
      isDrawer: true,
      rackLength: 0,
      drawerLength: 1),
  UnitData(
      unitId: 15,
      imageId: 1012,
      unitName: 'درفة وثابت',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isFixed: true),
  UnitData(
      unitId: 16,
      imageId: 1013,
      unitName: 'درفتين وثابت',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isFixed: true),
  UnitData(
      unitId: 17,
      imageId: 1015,
      unitName: 'درفة ودرفتين',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isMultiWidth: true,
      widthMultiShutterLength: 1,
      isNew: true),
  UnitData(
      unitId: 18,
      imageId: 1016,
      unitName: 'درفة ودرفتين',
      widthShutterLength: 1,
      heightShutterLength: 2,
      isMultiWidth: true,
      rackLength: 0,
      widthMultiShutterLength: 1,
      isNew: true),
  UnitData(
      unitId: 19,
      imageId: 1016,
      unitName: 'درفة ودرجين',
      widthShutterLength: 1,
      heightShutterLength: 2,
      isMultiWidth: true,
      rackLength: 0,
      isShutterWithDrawer: true,
      widthMultiShutterLength: 1,
      isNew: true),
  UnitData(
      unitId: 20,
      imageId: 1017,
      unitName: 'درفة وأدراج',
      isMultiWidth: true,
      isDrawer: true,
      withoutShutter: true,
      drawerLength: 4,
      rackLength: 0,
      isNew: true),
  UnitData(
      unitId: 21,
      imageId: 1018,
      unitName: 'درفتين وأدراج',
      isMultiWidth: true,
      isDrawer: true,
      withoutShutter: true,
      drawerLength: 4,
      rackLength: 0,
      widthMultiShutterLength: 2,
      isNew: true),
  UnitData(
      unitId: 22,
      imageId: 1019,
      unitName: '+ درجين ودرفة',
      isMultiWidth: true,
      isDrawer: true,
      drawerLength: 2,
      widthMultiShutterLength: 2,
      rackLength: 0,
      isNew: true),
  UnitData(
      unitId: 23,
      imageId: 1019,
      unitName: '+ درجين ودرج',
      isMultiWidth: true,
      isDrawer: true,
      isShutterWithDrawer: true,
      drawerLength: 2,
      widthMultiShutterLength: 2,
      rackLength: 0,
      isNew: true),
  UnitData(
      unitId: 24,
      imageId: 1020,
      unitName: '+ درجين علبة',
      heightShutterLength: 2,
      isMultiWidth: true,
      isShutterWithDrawer: true,
      widthMultiShutterLength: 2,
      rackLength: 0,
      isNew: true),
  UnitData(
      unitId: 25,
      imageId: 1020,
      unitName: '+ درفتين أفقي',
      heightShutterLength: 2,
      isMultiWidth: true,
      widthMultiShutterLength: 2,
      rackLength: 0,
      isNew: true),
  UnitData(
      unitId: 26,
      imageId: 1021,
      unitName: 'درفتين جرار',
      heightShutterLength: 1,
      widthShutterLength: 2,
      rackLength: 1,
      isSlide: true,
      isNew: true),
  UnitData(
      unitId: 27,
      imageId: 1022,
      unitName: 'سبت بامبو',
      withoutShutter: true,
      rackLength: 0,
      isBasket: true,
      isNew: true),
  UnitData(
      unitId: 28,
      imageId: 1023,
      unitName: 'بامبو بدرف',
      rackLength: 0,
      isBasket: true,
      isNew: true),
];
