import '../unit_data.dart';

List<UnitData> upperUnit = [
  UnitData(
    unitId: 0,
    imageId: 2001,
    unitName: 'درفة واحدة',
    widthShutterLength: 1,
    heightShutterLength: 1,
  ),
  UnitData(
    unitId: 1,
    imageId: 2002,
    unitName: 'درفة قلاب',
    widthShutterLength: 1,
    heightShutterLength: 1,
  ),
  UnitData(
    unitId: 2,
    imageId: 2003,
    unitName: 'درفتين',
    widthShutterLength: 2,
    heightShutterLength: 1,
  ),
  UnitData(
    unitId: 3,
    imageId: 2004,
    unitName: 'درفتين قلاب',
    widthShutterLength: 1,
    heightShutterLength: 2,
    rackLength: 0,
  ),
  UnitData(
      unitId: 4,
      imageId: 2005,
      unitName: 'درفة وثابت',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isFixed: true),
  UnitData(
      unitId: 5,
      imageId: 2010,
      unitName: 'درفتين وثابت',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isFixed: true),
  UnitData(
      unitId: 6,
      imageId: 2007,
      unitName: 'ميكرويف',
      widthShutterLength: 1,
      heightShutterLength: 1,
      rackLength: 0,
      isOpened: true),
  UnitData(
      unitId: 7,
      imageId: 2008,
      unitName: 'درفة وفراغ',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isOpened: true),
  UnitData(
      unitId: 8,
      imageId: 2009,
      unitName: 'درفتين وفراغ',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isOpened: true),
  UnitData(
      unitId: 9,
      imageId: 2006,
      unitName: 'أرفف مفتوحة',
      widthShutterLength: 1,
      heightShutterLength: 1,
      withoutShutter: true),
  UnitData(
      unitId: 10,
      imageId: 2011,
      unitName: 'درفة ودرفتين',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isMultiWidth: true,
      isNew: true),
  UnitData(
      unitId: 11,
      imageId: 2012,
      unitName: 'درفة ودرفتين',
      widthShutterLength: 1,
      heightShutterLength: 2,
      isMultiWidth: true,
      isNew: true),
  UnitData(
      unitId: 12,
      imageId: 2013,
      unitName: '+درفة وفراغ',
      widthShutterLength: 1,
      heightShutterLength: 1,
      isOpened: true,
      isMultiWidth: true,
      isNew: true),
  UnitData(
      unitId: 13,
      imageId: 2014,
      unitName: '+درفتين وفراغ',
      widthShutterLength: 2,
      heightShutterLength: 1,
      isOpened: true,
      isMultiWidth: true,
      isNew: true),
  UnitData(
      unitId: 14,
      imageId: 2015,
      unitName: 'قلاب ودرفتين',
      isWithTilt: true,
      widthShutterLength: 2,
      heightShutterLength: 1,
      isNew: true),
  UnitData(
      unitId: 15,
      imageId: 2016,
      unitName: 'درفتين وقلاب',
      isWithTilt: true,
      widthShutterLength: 2,
      heightShutterLength: 1,
      isNew: true),
];
